repos:
  - repo: local
    hooks:
      - id: isort
        name: Arrange imports and reformats code
        entry: make format
        language: system
        types: [python]
        require_serial: true

      - id: flake8
        name: Check code formatting using lint
        entry: make lint
        language: system
        types: [python]
        require_serial: true